version: "3.9"
services:
    app:
        build:
            context: ./
        container_name: app
        ports:
            - "5000:3000"
    nginx:
        build:
            context: ./nginx
        image: nginx
        container_name: nginx
        ports:
            - "8080:80"
        restart: always
