# This is a basic workflow to help you get started with Actions

name: Push

on:
  push:
    branches: 
      - master

  workflow_dispatch:

# env:
#   AWS_REGION: eu-west-1
#   ECR_ARN: 051206567486.dkr.ecr.eu-west-1.amazonaws.com
#   REGISTRY_ALIAS: devops-candidate

jobs:
  build:
    name: Build Docker image and push to Container Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v2
      
      # - name: Build container images
      #   run: |
      #     docker build -t app . 
      #     cd nginx && docker build -t nginx .

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, tag, and push docker image to Amazon ECR
      #   env:
      #     REGISTRY: ${{ env.ECR_ARN }}
      #     REGISTRY_ALIAS: ${{ env.REGISTRY_ALIAS }}
      #     REPOSITORY: app
      #   run: |
      #     docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY .
      #     docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: frontend
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile

      - name: Push To GitHub Container Registry
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/lmilbaum
          username: liora@lmb.co.il
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"