# This is a basic workflow to help you get started with Actions

name: Push

on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:
  build:
    name: Build Docker image and push to Container Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build frontend Image
        id: build-frontend-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: frontend
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile

      - name: Push To Dockerhub Container Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-frontend-image.outputs.image }}
          tags: ${{ steps.build-frontend-image.outputs.tags }}
          registry: registry-1.docker.io/lmilbaum
          username: lmilbaum
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Print frontend image url
        run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"

      - name: Build nginx Image
        id: build-nginx-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: nginx
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./nginx/Dockerfile

      - name: Push To Dockerhub Container Registry
        id: push-to-registry-nginx
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-nginx-image.outputs.image }}
          tags: ${{ steps.build-nginx-image.outputs.tags }}
          registry: registry-1.docker.io/lmilbaum
          username: lmilbaum
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Print nginx image url
        run: echo "Image pushed to ${{ steps.push-to-registry-nginx.outputs.registry-paths }}"
